name: Cypress E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e:
    runs-on: ubuntu-latest

    services:
      todomvc:
        image: dhruvd22/todomvc-app  
        ports:
          - 3000:3000
        options: >-
          --health-cmd="curl -f http://localhost:3000 || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install NPM Dependencies
        run: npm ci

      - name: Wait for App to Be Ready
        run: npx wait-on http://localhost:3000 --timeout 120000

      - name: Run Cypress Tests
        run: npm run cypress:run
        env:
          CI: true

      - name: Upload Screenshots on Failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Videos on Failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos
